config_file: /etc/redpanda/redpanda.yml
pandaproxy: {}
redpanda:
  admin:
    - address: 0.0.0.0
      port: 9644
  advertised_kafka_api:
    - address: broker1
      name: plaintext
      port: 29092
    - address: 127.0.0.1
      name: outside
      port: 9092
  data_directory: /var/lib/redpanda/data
  developer_mode: true
  group_initial_rebalance_delay: 300
  group_max_session_timeout_ms: 300000
  group_min_session_timeout_ms: 6000
  kafka_api:
    - address: 0.0.0.0
      name: plaintext
      port: 29092
    - address: 0.0.0.0
      name: outside
      port: 9092
  node_id: 0
  rpc_server:
    address: 0.0.0.0
    port: 33145
  seed_servers: []
rpk:
  coredump_dir: /var/lib/redpanda/coredump
  enable_memory_locking: false
  enable_usage_stats: false
  overprovisioned: true
  tune_aio_events: false
  tune_clocksource: false
  tune_coredump: false
  tune_cpu: false
  tune_disk_irq: false
  tune_disk_nomerges: false
  tune_disk_scheduler: false
  tune_disk_write_cache: false
  tune_fstrim: false
  tune_network: false
  tune_swappiness: false
  tune_transparent_hugepages: false
